//! Sanity check for the benchmark fixtures generated by
//! `examples/gen_fixtures.rs`: "none" must diff to nothing, "few"/"many"
//! must produce the expected number of update events, each a SERVICE or
//! ROUTE update, at every generated scale.

use std::path::PathBuf;

use adc_differ::DifferV4;
use adc_sdk::{EventType, InternalConfiguration, ResourceType};
use serde_json::Value;

/// Mirrors `SCALES` in `examples/gen_fixtures.rs`.
const SCALES: &[(&str, usize)] = &[("small", 100), ("medium", 1_000), ("large", 10_000)];

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../benches/fixtures")
}

fn load(name: &str) -> InternalConfiguration {
    let path = fixtures_dir().join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let v: Value = serde_json::from_slice(&bytes).unwrap();
    v.as_object().cloned().unwrap()
}

#[test]
fn none_scenario_has_no_diff_at_every_scale() {
    for &(scale, _) in SCALES {
        let local = load(&format!("{scale}.none.local.json"));
        let remote = load(&format!("{scale}.remote.json"));
        assert_eq!(DifferV4::diff(&local, &remote, None, None), vec![], "scale={scale}");
    }
}

#[test]
fn few_and_many_scenarios_produce_expected_update_events_at_every_scale() {
    for &(scale, count) in SCALES {
        for &(scenario, ratio) in &[("few", 0.05_f64), ("many", 0.5_f64)] {
            let local = load(&format!("{scale}.{scenario}.local.json"));
            let remote = load(&format!("{scale}.remote.json"));
            let events = DifferV4::diff(&local, &remote, None, None);

            // Each mutated service produces a SERVICE update (description changed)
            // + a ROUTE update (route-a's plugin changed) — see gen_fixtures.rs.
            let touched = (count as f64 * ratio).round() as usize;
            assert_eq!(events.len(), touched * 2, "scale={scale} scenario={scenario}");

            for event in &events {
                assert_eq!(event.event_type, EventType::Update, "scale={scale} scenario={scenario}");
                assert!(
                    matches!(event.resource_type, ResourceType::Service | ResourceType::Route),
                    "scale={scale} scenario={scenario}: unexpected resource_type on event {event:?}"
                );
            }
        }
    }
}
