//! Sanity check for the benchmark fixtures generated by
//! `examples/gen_fixtures.rs`: "none" must diff to nothing, "few"/"many"
//! must produce roughly the expected number of update events.

use std::path::PathBuf;

use adc_differ::DifferV4;
use adc_sdk::InternalConfiguration;
use serde_json::Value;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../benches/fixtures")
}

fn load(name: &str) -> InternalConfiguration {
    let path = fixtures_dir().join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let v: Value = serde_json::from_slice(&bytes).unwrap();
    v.as_object().cloned().unwrap()
}

#[test]
fn small_none_has_no_diff() {
    let local = load("small.none.local.json");
    let remote = load("small.remote.json");
    assert_eq!(DifferV4::diff(&local, &remote, None, None), vec![]);
}

#[test]
fn small_few_has_expected_update_count() {
    let local = load("small.few.local.json");
    let remote = load("small.remote.json");
    let events = DifferV4::diff(&local, &remote, None, None);
    // 100 services * 5% touched = 5 mutated services, each producing a SERVICE
    // update (description changed) + a ROUTE update (route-a's plugin changed).
    assert_eq!(events.len(), 10);
}

#[test]
fn small_many_has_expected_update_count() {
    let local = load("small.many.local.json");
    let remote = load("small.remote.json");
    let events = DifferV4::diff(&local, &remote, None, None);
    // 100 services * 50% touched = 50 mutated services, each producing a SERVICE
    // update (description changed) + a ROUTE update (route-a's plugin changed).
    assert_eq!(events.len(), 100);
}
