builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
    - amd64
    - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -X github.com/api7/adc/cmd.VERSION={{ .Tag }} -X github.com/api7/adc/cmd.GitRevision={{ .Commit }}
archives:
  - format: tar.gz
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
