packages:
  - apps/*
  - libs/*

catalogMode: strict
catalog:
  tslib: ^2.6.2
  axios: 1.13.2
  zod: ^4.1.12
  rxjs: ^7.8.2
  immer: ^10.2.0
  lodash: ^4.17.21
  "@types/lodash": ^4.17.4
  semver: ^7.7.3
  "@types/semver": ^7.7.1
  vitest: ^4.0.13
  "@vitest/ui": ^4.0.13
  "@vitest/coverage-v8": ^4.0.13
  "deep-diff": ^1.0.2
  "@types/deep-diff": ^1.0.5

minimumReleaseAge: 1440
