name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug!

        _The more information you share, the faster we can identify and fix the bug._

        Please check the [open issues](https://github.com/api7/adc/issues) to avoid duplication.
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe the issue with the current behavior.
      placeholder: |
        When I run `adc sync` I get an error message...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Exxpected Behavior
      description: Describe what you expected to happen instead.
      placeholder: |
        Instead of the error, I expect `adc sync` to...
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Share how we can reproduce this issue. Reports without proper steps are likely to be closed.
      placeholder: |
        1. Run `adc configure`
        2. Run `adc sync` with this configuration file
        3. Check APISIX if the configuration is applied
        4. ...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Share your environment details. Reports without proper environment details are likely to be closed.
      value: |
        - APISIX version:
        - ADC version (run `adc version`):
        - Operating system (run `uname -a`):
    validations:
      required: true
