name: Improve Documentation
description: Suggest an improvement to the documentation
title: "Docs: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest an improvement to the documentation.

        Please check the [open issues](https://github.com/api7/adc/issues) to avoid duplication.
  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: Describe the current state of the documentation.
      placeholder: |
        The documentation for the command... is missing...
    validations:
      required: true
  - type: textarea
    id: desired-state
    attributes:
      label: Desired State
      description: Describe the desired state of the documentation.
      placeholder: |
        The documentation should mention how to use the command... for...
    validations:
      required: true
