[package]
name = "adc-mock-server"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[[bin]]
name = "adc-mock-server"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "signal"] }
axum = "0.8"
