name: Run CLI E2E Test Suites

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main
      - release/**
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            src:
              - '*.go'
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
              - 'Makefile'
              - '.github/**'
              - 'internal/**'
  run-test:
    needs: changes
    if: |
      (needs.changes.outputs.src == 'true')
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.3'

      - name: Install ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo
          sudo cp ~/go/bin/ginkgo /usr/local/bin

      - name: Build ADC
        working-directory: ./
        run: |
          make build

      - name: Deploy Apache APISIX
        run: |
          sh utils/quickstart.sh
          docker run --name httpbin --network apisix-quickstart-net --hostname httpbin -d kennethreitz/httpbin

      - name: Run E2E Test Suites
        working-directory: ./
        run: |
          export PATH=$PWD/bin:$PATH
          make test
