name: Docker Release
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@5f637c833aa76bc99372a1dc9a6f8bcd8056fb85 # v1.12.0
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: ${{ github.event_name == 'push' }}
      platforms: linux/amd64,linux/arm64
      file: libs/tools/src/docker/Dockerfile
      meta-images: |
        docker.io/api7/adc
        ghcr.io/api7/adc
      meta-tags: |
        type=semver,pattern={{version}}
        type=raw,value=dev,enable={{is_default_branch}}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
        - registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
