name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  adc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup release flow
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      # Build and test ADC CLI
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: pnpm/action-setup@v4
      - name: Build ADC
        env:
          NODE_VERSION: 22.17.0
        run: |
          pnpm install
          NODE_ENV=production npx nx build cli
          node --experimental-sea-config apps/cli/node-sea.json
          npx ts-node apps/cli/scripts/download-node.ts
          npx postject ./node-binary/linux-amd64 NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
          npx postject ./node-binary/linux-arm64 NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
          npx postject ./node-binary/win-x64.exe NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
          npx postject ./node-binary/win-arm64.exe NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2

      - name: Compress ADC
        run: |
          mkdir -p release
          mv ./node-binary/linux-amd64 ./adc
          tar -czf release/adc_${{ env.RELEASE_VERSION }}_linux_amd64.tar.gz ./adc && rm -rf ./adc
          mv ./node-binary/linux-arm64 ./adc
          tar -czf release/adc_${{ env.RELEASE_VERSION }}_linux_arm64.tar.gz ./adc && rm -rf ./adc
          mv ./node-binary/win-x64.exe ./adc.exe
          zip -r release/adc_${{ env.RELEASE_VERSION }}_windows_amd64.zip ./adc.exe && rm -rf ./adc.exe
          mv ./node-binary/win-arm64.exe ./adc.exe
          zip -r release/adc_${{ env.RELEASE_VERSION }}_windows_arm64.zip ./adc.exe && rm -rf ./adc.exe

      - name: Upload ADC to GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/adc_${{ env.RELEASE_VERSION }}_linux_amd64.tar.gz
            release/adc_${{ env.RELEASE_VERSION }}_linux_arm64.tar.gz
            release/adc_${{ env.RELEASE_VERSION }}_windows_amd64.zip
            release/adc_${{ env.RELEASE_VERSION }}_windows_arm64.zip

  adc-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Setup release flow
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      # Build and test ADC CLI
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Build ADC
        run: |
          pnpm install
          NODE_ENV=production npx nx build cli
          node --experimental-sea-config apps/cli/node-sea.json
          npx ts-node apps/cli/scripts/download-node.ts
          codesign --remove-signature ./node-binary/darwin-arm64
          codesign --remove-signature ./node-binary/darwin-x64
          npx postject ./node-binary/darwin-arm64 NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 --macho-segment-name NODE_SEA
          npx postject ./node-binary/darwin-x64 NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 --macho-segment-name NODE_SEA
          codesign --sign - ./node-binary/darwin-arm64
          codesign --sign - ./node-binary/darwin-x64

      - name: Compress ADC
        run: |
          mkdir release
          mv ./node-binary/darwin-arm64 ./adc
          tar -czf release/adc_${{ env.RELEASE_VERSION }}_darwin_arm64.tar.gz ./adc && rm -rf ./adc
          mv ./node-binary/darwin-x64 ./adc
          tar -czf release/adc_${{ env.RELEASE_VERSION }}_darwin_amd64.tar.gz ./adc && rm -rf ./adc

      - name: Upload ADC to GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/adc_${{ env.RELEASE_VERSION }}_darwin_arm64.tar.gz
            release/adc_${{ env.RELEASE_VERSION }}_darwin_amd64.tar.gz
