name: Rust Windows Build
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - "rust/**"
      - ".github/workflows/rust-windows-build.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "rust/**"
      - ".github/workflows/rust-windows-build.yaml"
jobs:
  adc-rust-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            arch: amd64
          - os: windows-11-arm
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Rust toolchain
        shell: bash
        run: |
          rustup update stable
          rustup default stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: rust -> target
          key: ${{ matrix.arch }}
      - name: Build adc-cli
        working-directory: ./rust
        run: cargo build --release -p adc-cli

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: adc-rust-windows-${{ matrix.arch }}
          path: rust/target/release/adc.exe
          if-no-files-found: error
