name: Update S3 and Cloudfront
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-s3-and-cloudfront.yaml
      - libs/tools/project.json
      - libs/tools/src/s3/install
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/update-s3-and-cloudfront.yaml
      - libs/tools/project.json
      - libs/tools/src/s3/install

jobs:
  update-s3-and-cloudfront:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          role-to-assume: ${{ secrets.AWS_QUICKSTART_ROLE }}
          aws-region: us-west-2

      - name: Deploy
        if: github.event_name == 'push'
        # The path to the install script will be /adc/install
        run: aws s3 sync ./libs/tools/src/s3 s3://api7ai-docs-resources/adc

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@6adb1f613f4102ad81cd08a7ba83b8abe490cb8d # v2.4.2
        if: github.event_name == 'push'
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: /adc/install
